# Generated by Django 3.1.3 on 2023-04-05 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Place',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=10)),
                ('pname', models.TextField()),
                ('location', models.TextField()),
                ('number', models.IntegerField(default=0)),
            ],
        ),
    ]
