# Generated by Django 3.1.3 on 2023-04-06 10:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='place',
            old_name='number',
            new_name='price',
        ),
    ]
