# Generated by Django 3.1.3 on 2023-04-07 07:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0002_auto_20230406_1915'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='imgfile',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='place',
            name='modify_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
