# Generated by Django 3.1.3 on 2023-04-12 07:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0004_place_author'),
    ]

    operations = [
        migrations.AddField(
            model_name='place',
            name='ball',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='side',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='place',
            name='vest',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
