# Generated by Django 3.1.3 on 2023-04-12 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rent', '0005_auto_20230412_1616'),
    ]

    operations = [
        migrations.CreateModel(
            name='RentInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pcode', models.CharField(max_length=10)),
                ('pname', models.TextField()),
                ('price', models.IntegerField(default=0)),
                ('r_date', models.DateTimeField()),
            ],
        ),
    ]
